add_library(ParticleSaturnOpenGL41Backend STATIC OpenGL41Surface.mm OpenGLParticleSystem.mm)
add_library(ParticleSaturn.Backend.OpenGL41 ALIAS ParticleSaturnOpenGL41Backend)
target_include_directories(ParticleSaturnOpenGL41Backend PUBLIC "${CMAKE_CURRENT_LIST_DIR}/../../..")
target_compile_definitions(ParticleSaturnOpenGL41Backend PRIVATE GL_SILENCE_DEPRECATION=1)
target_link_libraries(ParticleSaturnOpenGL41Backend PUBLIC "-framework Cocoa" "-framework OpenGL")

if(BUILD_TESTING)
    add_executable(ParticleSaturnOpenGLParticleTests "${CMAKE_SOURCE_DIR}/tests/OpenGLParticleSystemTests.mm")
    target_compile_definitions(ParticleSaturnOpenGLParticleTests PRIVATE GL_SILENCE_DEPRECATION=1)
    target_link_libraries(ParticleSaturnOpenGLParticleTests PRIVATE ParticleSaturnOpenGL41Backend)
    add_dependencies(ParticleSaturnOpenGLParticleTests ParticleSaturnOpenGL41Shaders)
    add_test(NAME ParticleSaturnOpenGLParticleTests COMMAND ParticleSaturnOpenGLParticleTests "${CMAKE_SOURCE_DIR}/src/shaders/glsl410/ParticleSimulationTF.vert")
endif()
