if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "INPUT and OUTPUT_DIRECTORY are required")
endif()

file(READ "${INPUT}" ABI_JSON)
string(JSON ABI_NAME GET "${ABI_JSON}" name)
string(JSON ABI_SIZE GET "${ABI_JSON}" size)
string(JSON ABI_FIELD_COUNT LENGTH "${ABI_JSON}" fields)
math(EXPR ABI_LAST_FIELD "${ABI_FIELD_COUNT} - 1")

set(CPP_FIELDS "")
set(HLSL_FIELDS "")
set(GLSL_FIELDS "")
foreach(INDEX RANGE ${ABI_LAST_FIELD})
    string(JSON FIELD_NAME GET "${ABI_JSON}" fields ${INDEX} name)
    string(JSON FIELD_TYPE GET "${ABI_JSON}" fields ${INDEX} type)
    if(FIELD_TYPE STREQUAL "float4")
        set(CPP_TYPE "float ${FIELD_NAME}[4]")
        set(HLSL_TYPE "float4")
        set(GLSL_TYPE "vec4")
    elseif(FIELD_TYPE STREQUAL "float")
        set(CPP_TYPE "float ${FIELD_NAME}")
        set(HLSL_TYPE "float")
        set(GLSL_TYPE "float")
    elseif(FIELD_TYPE STREQUAL "uint")
        set(CPP_TYPE "std::uint32_t ${FIELD_NAME}")
        set(HLSL_TYPE "uint")
        set(GLSL_TYPE "uint")
    else()
        message(FATAL_ERROR "unsupported ABI field type: ${FIELD_TYPE}")
    endif()
    string(APPEND CPP_FIELDS "    ${CPP_TYPE};\n")
    string(APPEND HLSL_FIELDS "    ${HLSL_TYPE} ${FIELD_NAME};\n")
    string(APPEND GLSL_FIELDS "    ${GLSL_TYPE} ${FIELD_NAME};\n")
endforeach()

file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT_DIRECTORY}/${ABI_NAME}Abi.h" "#pragma once\n\n#include <cstdint>\n\nnamespace ParticleSaturn::ShaderAbi {\n\nstruct alignas(16) ${ABI_NAME} {\n${CPP_FIELDS}};\nstatic_assert(sizeof(${ABI_NAME}) == ${ABI_SIZE});\n\n} // namespace ParticleSaturn::ShaderAbi\n")
file(WRITE "${OUTPUT_DIRECTORY}/${ABI_NAME}.hlsl" "struct ${ABI_NAME} {\n${HLSL_FIELDS}};\n")
file(WRITE "${OUTPUT_DIRECTORY}/${ABI_NAME}.glsl" "struct ${ABI_NAME} {\n${GLSL_FIELDS}};\n")
